### ISSUE TITLE
Payload:

### ISSUE THREAD

**Issue by Trey432** [ryandotclair/conductor#2]
Recieving payload: {'AlertType': 1, 'AlertName': 'Test1', 'SearchPeriod': 300000, 'HitCount': 0.0, 'HitOperator': 2, 'messages': [], 'HasMoreResults': False, 'Url': None, 'EditUrl': None, 'Info': None, 'Recommendation': None, 'NumHits': 0}
{'AlertType': 1, 'AlertName': 'Test1', 'SearchPeriod': 300000, 'HitCount': 0.0, 'HitOperator': 2, 'messages': [], 'HasMoreResults': False, 'Url': None, 'EditUrl': None, 'Info': None, 'Recommendation': None, 'NumHits': 0}
192.168.110.24 - - [16/Dec/2017 16:03:16] "POST /api/workflow HTTP/1.1" 500 -
Traceback (most recent call last):

**Comment by ryandotclair** [comment]
Fixed.
